name: Run 189cn

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # 每天UTC时间凌晨0点运行一次，北京时间会是当天早上 8:55 ~ 9:25
  push:
    branches:
      - main
jobs:
  login:
    runs-on: ubuntu-22.04 #ubuntu-latest

    steps:
      - name: Checkout 仓库代码
        uses: actions/checkout@v2

      - name: 设置 Python 环境
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.x'  # 设置你希望使用的 Python 版本，建议使用稳定版本

      - name: Create accounts.json from environment variable
        run: echo "$ACCOUNTS_JSON" > accounts.json
        env:
            ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}  # 从GitHub Secrets中获取环境变量

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv rsa push_tools dict2str

      - name: 运行登录脚本
        env:
          USERNAME189: ${{ secrets.USERNAME189 }}  #
          PASSWORD189: ${{ secrets.PASSWORD189 }}  #
          ty_username: ${{ secrets.TY_USERNAME }}  #
          ty_password: ${{ secrets.TY_PASSWORD }}  #
          XIANYUDANJIUSER: ${{ secrets.XIANYUDANJIUSER}}
          XIANYUDANJIPASS: ${{ secrets.XIANYUDANJIPASS}}
        run: |
          python tianyiyun.py # python index.py
          python xianyudanji.py
